# Deep Learning Using Tensorflow

- TensorFlow is an open-source machine learning framework developed by google.

In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

2.19.0


## Tensor
- Tensors are multidimensional arrays.
- Understanding key concepts like tensor, shape, size, rank and dimension.

**Creating tensors with tf.constant()**

In [3]:
# create a tensor with tf.constant()
tensor =  tf.constant([[1,2,3],
                        [4,5,6]])
print(tensor)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [4]:
# tensor shape refers to the layout or structure of a tensor.
print(tensor.shape)

(2, 3)


In [5]:
# dimension
print(f"The number of dimension: {tensor.ndim}")
print(f"Length of first dimension: {tensor.shape[0]}")
print(f"Length of second dimension: {tensor.shape[1]}")

The number of dimension: 2
Length of first dimension: 2
Length of second dimension: 3


In [6]:
# tensor size refers to the total number of elements in a tensor.
print(tf.size(tensor))

tf.Tensor(6, shape=(), dtype=int32)


In [7]:
# tensor rank
# It indicates the number of dimensions present in a tensor.
"""
  Brief overview of tensor rank:
  Rank 0: Scalar
  Rank 1: Vectors
  Rank 2: Matrices
  Rank 3 and above: 3 or more dimension and represent higher-dimensional arrays of values
"""
scalar = tf.constant(20) # salar.ndim (It will give the number of dimension)
vector = tf.constant([2,3,5])
matrix = tf.constant([[1,2,3,5],[6,7,8,9]])
tensor_3d = tf.constant([[[1,10],[2,20]],[[3,30],[4,40]]])

print(f"Rank of Scalar: {tf.rank(scalar)}")
print(f"Rank of Vector: {tf.rank(vector)}")
print(f"Rank of Matrix: {tf.rank(matrix)}")
print(f"Rank of tensor: {tf.rank(tensor_3d)}")

Rank of Scalar: 0
Rank of Vector: 1
Rank of Matrix: 2
Rank of tensor: 3


**Creating tensors with tf.Variable**

In [8]:
changeable_tensor = tf.Variable([10.,7.])
unchangeable_tensor = tf.constant([10,7])

In [9]:
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([10.,  7.], dtype=float32)>

In [10]:
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [11]:
# change element in changeable_tensor using .assign()
changeable_tensor[0].assign(20)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=float32, numpy=array([20.,  7.], dtype=float32)>

**KeyNote**: Rarely in practise will you need to decide whether to use tf.constant or tf.Variable to create tensors, as TensorFlow does this for you. However,if in doubt, use tf.constant and change it later if needed

**Creating Random Tensors**
- Random tensors are tensors of some arbitary size which contain random numbers

In [12]:
# creating 2 random but same tensors
random_1 = tf.random.Generator.from_seed(42) # seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42) # seed for reproducibility
random_2 = random_2.normal(shape=(3,2))

# equality check?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [13]:
random_3 = tf.random.Generator.from_seed(42) # seed for reproducibility
random_3 = random_3.uniform(shape=(3,2))
random_3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

**Shuffle the order of elements in a tensor**

In [17]:
# shuffle a tensor
matrix = tf.constant([[10,7],
                      [3,4],
                      [2,5]])
tf.random.shuffle(matrix)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [21]:
tf.random.set_seed(42) # global level random seed
tf.random.shuffle(matrix) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

**Other Ways to make tensor**

In [22]:
# Create a tensor
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [23]:
tf.zeros([6,9])

<tf.Tensor: shape=(6, 9), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

**Creating tensors form Numpy arrays**

In [24]:
import numpy as np
numpy_A =  np.arange(1,25,dtype=np.float32)
numpy_A

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
      dtype=float32)

In [25]:
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
 array([[[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]],
 
        [[13., 14., 15., 16.],
         [17., 18., 19., 20.],
         [21., 22., 23., 24.]]], dtype=float32)>,
 <tf.Tensor: shape=(24,), dtype=float32, numpy=
 array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.],
       dtype=float32)>)

In [26]:
# create a rank 4 tensor (4 dimension)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
print("Datatype of every element: ",rank_4_tensor.dtype)
print("Number of dimensions (rank): ",rank_4_tensor.ndim)
print("Shape of tensor: ",rank_4_tensor.shape)
print("Elements along the 0 axis: ",rank_4_tensor.shape[0])
print("Elements along the last axis: ",rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ",tf.size(rank_4_tensor))


Datatype of every element:  <dtype: 'float32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)


**Indexing and manipulating**

- Tensors can be indexed just like python list.

In [31]:
# get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [32]:
rank_4_tensor[:1,:1,:1,:2]

<tf.Tensor: shape=(1, 1, 1, 2), dtype=float32, numpy=array([[[[0., 0.]]]], dtype=float32)>

In [36]:
# add a new dimension to the tensor
# create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.Variable([[10,23],
                             [32,43]])
rank_2_tensor.shape

TensorShape([2, 2])

In [37]:
# get the last item of each of row of the rank_2_tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([23, 43], dtype=int32)>

In [38]:
# adding a new axis to create a new one
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [23]],

       [[32],
        [43]]], dtype=int32)>

In [39]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor,axis=-1) #"-1" means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [23]],

       [[32],
        [43]]], dtype=int32)>

In [40]:
tf.expand_dims(rank_2_tensor,axis=0) #"0" means expand the final axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10, 23],
        [32, 43]]], dtype=int32)>

In [42]:
# Manipulating tensors (tensor operations)
# basic operations: + , - , *, /
# adding values
tensor = tf.constant([[10,3],[12,42]])

In [43]:
tensor+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 13],
       [22, 52]], dtype=int32)>

In [44]:
tensor - 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, -2],
       [ 7, 37]], dtype=int32)>

In [45]:
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  30],
       [120, 420]], dtype=int32)>

In [46]:
tensor / 2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 5. ,  1.5],
       [ 6. , 21. ]])>

In [47]:
# using tensorflow built-in function too
tf.multiply(tensor, 2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20,  6],
       [24, 84]], dtype=int32)>

- Matrix Multiplication

In [50]:
a = tf.constant([[10,20],
                 [40,50]])
print(a)
tf.matmul(a,a)

tf.Tensor(
[[10 20]
 [40 50]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 900, 1200],
       [2400, 3300]], dtype=int32)>

In [51]:
a * a # element wise multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 100,  400],
       [1600, 2500]], dtype=int32)>

In [52]:
# matrix multiplication with Python operator '@'
a @ a

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 900, 1200],
       [2400, 3300]], dtype=int32)>

In [53]:
X = tf.constant([[1,2],
                 [3,4],
                 [5,6]])
Y = tf.constant([[7,8],
                 [9,10],
                 [11,12]])
X , Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [54]:
X @ Y

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [55]:
tf.matmul(X, Y, transpose_b=True)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [56]:
tf.matmul(X, tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [58]:
X

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [57]:
# reshaping tensor vs transposing tensor
tf.transpose(X), tf.reshape(X, shape=(2,3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>)

- matrix multiplication can perform in different way:
  - tf.matmul()
  - tf.tensordot()
  - a @ A

**Changing datatypes**

In [61]:
A = tf.constant([12.,32.2])
A

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([12. , 32.2], dtype=float32)>

In [63]:
# change from float32 to float16 (reduce precision)
B = tf.cast(A, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([12. , 32.2], dtype=float16)>

**Aggregating Tensor**
- condesing them from multiple values down to a smaller amount of values

In [64]:
C = tf.constant([-2,-23.4])
C

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ -2. , -23.4], dtype=float32)>

In [65]:
tf.abs(C)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 2. , 23.4], dtype=float32)>

Lets go through the following form of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [67]:
import numpy as np
# let's create large tensor
E = tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([65, 58, 97,  5, 36, 18,  7, 28, 97,  6, 74, 37,  3, 98, 94,  8,  8,
       96, 77, 19, 43,  7, 44, 97, 33, 70, 79, 55, 23, 99, 57, 55, 38,  6,
        8, 91, 59, 78, 48, 50, 87, 68, 56, 78, 44, 43, 93, 47, 76, 39])>

In [68]:
# find the minimum of the tensor
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [70]:
# Find the maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [71]:
# Find the sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2602>

In [72]:
# Find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=52>

- find the positional maximum and minimum

In [74]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [75]:
# Find the positional Maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [77]:
# index on the maximum value
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [78]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [80]:
F[tf.argmin(F)] # the minimum value using the positional minimum index

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

**Squeezing a tensor**

In [81]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [82]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [83]:
G_squeez = tf.squeeze(G) # Removes dimensions of size 1 from the shape of a tensor.
G_squeez

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

**One-hot Encoding**

In [88]:
some_list = [0,1,2,3,4]
tf.one_hot(some_list, depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>